source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"
inhibit_all_warnings!

pod 'Masonry', '~> 0.5.3'
pod 'KVOController', '~> 1.0.3'
pod 'SDWebImage', '~> 3.7.1'
pod 'AFNetworking-RACExtensions', '~> 0.1.6'
pod 'UberKit', '~> 0.1.0'
pod "MagicalRecord"